{:user {:plugins [[cider/cider-nrepl       "0.8.1"]
                  [jonase/eastwood         "0.2.4" :exclusions [org.clojure/clojure]]
                  [lein-ancient            "0.6.8"]
                  [lein-bikeshed           "0.4.1"]
                  [lein-cljfmt             "0.5.7"]
                  [lein-deps-tree          "0.1.2"]
                  [lein-exec               "0.3.0"]
                  [lein-kibit              "0.1.5"]
                  [lein-localrepo          "0.5.2"]
                  [lein-midje              "3.1.3"]
                  [lein-try                "0.4.3"]
                  [org.clojure/tools.trace "0.7.9"]
                  [s3-wagon-private        "1.1.2"]
                  [venantius/ultra         "0.5.1"]]
        :dependencies [[alembic "0.3.2"]
                       [cljfmt  "0.5.1"]
                       [criterium "0.4.3"]]
        :aliases {"slamhound" ["run" "-m" "slam.hound"]}
        :repl-options {:init (require 'cljfmt.core)}}}
